-- USER table
CREATE TABLE USER (
    UserID INTEGER PRIMARY KEY AUTOINCREMENT,
    Username TEXT NOT NULL,
    Password TEXT NOT NULL,
    FullName TEXT,
    Qualification TEXT,
    DOB DATE,
    IsAdmin BOOLEAN DEFAULT 0
);

-- SUBJECT table
CREATE TABLE SUBJECT (
    SubjectID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    Description TEXT,
    ChapterID INTEGER,
    FOREIGN KEY (ChapterID) REFERENCES CHAPTER(ChapterID)
);

-- CHAPTER table
CREATE TABLE CHAPTER (
    ChapterID INTEGER PRIMARY KEY AUTOINCREMENT,
    ChapterName TEXT NOT NULL,
    Content TEXT,
    QuestionID INTEGER,
    FOREIGN KEY (QuestionID) REFERENCES QUESTIONS(QuestionID)
);

-- QUESTIONS table
CREATE TABLE QUESTIONS (
    QuestionID INTEGER PRIMARY KEY AUTOINCREMENT,
    Type TEXT,
    Question TEXT NOT NULL,
    Solution TEXT
);

-- QUIZ table
CREATE TABLE QUIZ (
    QuizID INTEGER PRIMARY KEY AUTOINCREMENT,
    SubjectID INTEGER,
    QuestionID INTEGER,
    TimeStamp DATETIME,
    Duration INTEGER,
    TotalMark INTEGER,
    FOREIGN KEY (SubjectID) REFERENCES SUBJECT(SubjectID),
    FOREIGN KEY (QuestionID) REFERENCES QUESTIONS(QuestionID)
);

-- SCORES table
CREATE TABLE SCORES (
    QuizID INTEGER,
    UserID INTEGER,
    MarksReceived INTEGER,
    PRIMARY KEY (QuizID, UserID),
    FOREIGN KEY (QuizID) REFERENCES QUIZ(QuizID),
    FOREIGN KEY (UserID) REFERENCES USER(UserID)
);
